export const userParams = [
    { label: 'login', value: 'Login' },
    { label: '_id', value: 'ID' },
    { label: 'email', value: 'Email' },
    { label: 'name', value: 'Имя' },
    { label: 'avatarUrl', value: 'Аватар' },
    { label: 'reminders', value: 'Напоминания' },
    { label: 'emailReminders', value: 'На почту' },
    { label: 'smsReminders', value: 'По SMS' },
    { label: 'reminderDaysBefore', value: 'За сколько дней до' },
    { label: 'preferredHour', value: 'Время отправки' },
    { label: 'timeZone', value: 'Часовой пояс' },
    { label: 'twoFactorAuth', value: 'Двухфакторка' },
    { label: 'lastPasswordChange', value: 'Последняя смена пароля' },
    { label: 'emailVerified', value: 'Проверка почты' },
    { label: 'lastSendTime', value: 'Последняя отправка' },
    { label: 'role', value: 'Роль' },
    { label: 'createdAt', value: 'Дата создания' },
]

export const groupsParams = {
    notChangeFields: ['login', '_id'],
    inputFields: ['email', 'name', 'avatarUrl'],
    timeFields: ['lastPasswordChange', 'lastSendTime', 'createdAt'],
    dropdownFields: [
        'reminders', 
        'emailReminders', 
        'smsReminders', 
        'twoFactorAuth',
        'emailVerified',
        'preferredHour',
        'reminderDaysBefore',
        'timeZone', 
        'role',
    ],
}

export const valueParams = {
    booleanParams: [
        { label: true, value: 'Да' },
        { label: false, value: 'Нет' },
    ],
    reminderDaysBefore: [
        { value: 1 },
        { value: 2 },
        { value: 3 },
        { value: 4 },
        { value: 5 },
        { value: 6 },
        { value: 7 },
    ],
    preferredHour: [
        { value: '10:00' },
        { value: '12:00' },
        { value: '15:00' },
        { value: '18:00' },
        { value: '20:00' },
    ],
    timeZone: [
        { value: 'Europe/London' },
        { value: 'Europe/Paris' },
        { value: 'Europe/Berlin' },
        { value: 'Europe/Moscow' },
        { value: 'Asia/Dubai' },
        { value: 'Asia/Tehran' },
        { value: 'Asia/Kolkata' },
        { value: 'Asia/Bangkok' },
        { value: 'Asia/Shanghai' },
        { value: 'Asia/Singapore' },
        { value: 'Asia/Tokyo' },
        { value: 'Australia/Sydney' },
        { value: 'Pacific/Auckland' },
        { value: 'Pacific/Fiji' },
        { value: 'America/Anchorage' },
        { value: 'America/Los_Angeles' },
        { value: 'America/Denver' },
        { value: 'America/Chicago' },
        { value: 'America/New_York' },
        { value: 'America/Sao_Paulo' },
        { value: 'America/Argentina/Buenos_Aires' },
        { value: 'America/Lima' },
        { value: 'Africa/Cairo' },
        { value: 'Africa/Nairobi' },
    ],
    role: [
        {value: 'user'},
        {value: 'admin'},
    ]
};